# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "My Portfolio"
title_separator          : "-"
name                     : "Jarmo Syvälahti"
description              : "A portfolio of projects by Jarmo Syvälahti."
url                      : "https://jarm111.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "jarm111/jarm111.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/j111.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title

# Site Author
author:
  name             : "Jarmo Syvälahti"
  avatar           : "/assets/images/j111.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "An aspiring web developer."
  location         : "Jyväskylä, Finland"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: mailto:your.name@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jarm111/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/jarmosyvalahti"

plugins:
  - jekyll-include-cache